<header class="header">
    <div class="header-block header-block-search hidden-sm-down">
        <form role="search">
            <div class="input-container"> 
                <i class="fa fa-search"></i> 
                <input type="search" placeholder="Search">
                <div class="underline"></div>
             </div>
        </form>
    </div>
    <div class="header-block header-block-nav">
        <ul class="nav-profile">
            <li class="profile dropdown">
                <a href="#" class="nav-link dropdown-toggle">
                    <div style="width: 30px;background-image: url('/static/images/logo-100.png')" class="img"></div>
                    <span class="name"><?php echo $username ?></span> 
                </a>
            </li>
        </ul>
    </div>
</header>
